# 容器 配置
server:
  port: 8180
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

# 数据库 及 Redis 配置    
spring:
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/ictgu?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: localhost%pwd123
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10
  mail:
    host: smtp.ym.163.com
    username: pksurecom@163.com
    password: 123456
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: false
          required: false

# Mybatis 配置
mybatis:
  config-location: classpath:/mybatis.xml

# Redis Key 前缀
redis:
  prefix:
    signUp: SIGN

# 本站信息
app:
  name: 沧海云
  domain: ictgu.cn
